# Generated by Django 5.2.17 on 2026-09-10 16:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='teachers_avatars/')),
                ('bio', models.TextField(blank=True)),
                ('timezone', models.CharField(default='Europe/Warsaw', max_length=64)),
                ('language', models.CharField(default='pl', max_length=10)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('default_lesson_duration', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15)])),
                ('default_lesson_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
