# Generated by Django 5.2.17 on 2026-09-27 08:52

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_studentsubject'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('max_students', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_groups', to='academics.subject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_groups', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('name', 'id'),
                'indexes': [models.Index(fields=['workspace', 'is_active'], name='group_ws_active_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('workspace'), name='unique_group_name_per_ws_ci'), models.CheckConstraint(condition=models.Q(('max_students__isnull', True), ('max_students__gte', 1), _connector='OR'), name='group_max_students_positive')],
            },
        ),
    ]
