# Generated by Django 5.2.17 on 2026-09-27 18:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_group'),
        ('students', '0003_student_archived_at_student_status_before_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='academics.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='students.student')),
            ],
            options={
                'ordering': ('-joined_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='study_groups', through='academics.GroupMembership', through_fields=('group', 'student'), to='students.student'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'left_at'], name='gm_group_left_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('group', 'student'), name='unique_active_group_member'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(condition=models.Q(('left_at__isnull', True), ('left_at__gte', models.F('joined_at')), _connector='OR'), name='group_member_valid_dates'),
        ),
    ]
