# Generated by Django 5.2.17 on 2026-09-25 12:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('default_lesson_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'id'),
                'indexes': [models.Index(fields=['workspace', 'status'], name='student_ws_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('default_lesson_price__gte', 0), ('default_lesson_price__isnull', True), _connector='OR'), name='student_price_non_negative')],
            },
        ),
    ]
