# Generated by Django 5.2.17 on 2026-09-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_studentsubject'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', through='academics.StudentSubject', through_fields=('student', 'subject'), to='academics.subject'),
        ),
    ]
