# Generated by Django 5.2.17 on 2026-09-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status_before_archive',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
