# Generated by Django 5.2.17 on 2026-10-02 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_groupmembership_group_students_and_more'),
        ('lessons', '0004_lesson_attendance_initialized_at_lessonattendance'),
        ('students', '0003_student_archived_at_student_status_before_archive'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.group')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='lessons.lesson')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_assignments', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.subject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
                'indexes': [models.Index(fields=['workspace', 'status', 'due_at'], name='hw_ws_status_due_idx'), models.Index(fields=['workspace', 'created_at'], name='hw_ws_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('student__isnull', False)), models.Q(('group__isnull', False), ('student__isnull', True)), _connector='OR'), name='hw_assignment_one_target'), models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('status', 'draft')), models.Q(('due_at__isnull', False), ('published_at__isnull', False), ('status__in', ['published', 'closed'])), _connector='OR'), name='hw_assignment_publication_state'), models.CheckConstraint(condition=models.Q(('due_at__isnull', True), ('published_at__isnull', True), ('due_at__gt', models.F('published_at')), _connector='OR'), name='hw_assignment_due_after_publish')],
            },
        ),
    ]
