# Generated by Django 5.2.17 on 2026-10-02 12:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_groupmembership_group_students_and_more'),
        ('homework', '0001_initial'),
        ('students', '0003_student_archived_at_student_status_before_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('snapshot', 'Publication snapshot'), ('manual', 'Manual assignment')], default='snapshot', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='homework.assignment')),
                ('group_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_recipients', to='academics.groupmembership')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_recipients', to='students.student')),
            ],
            options={
                'ordering': ('student__last_name', 'student__first_name', 'id'),
                'indexes': [models.Index(fields=['student', 'assigned_at'], name='hw_rec_student_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student'), name='hw_unique_assignment_recipient'), models.CheckConstraint(condition=models.Q(('source__in', ['snapshot', 'manual'])), name='hw_recipient_valid_source')],
            },
        ),
    ]
