# Generated by Django 5.2.17 on 2026-10-02 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_assignmentrecipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='submitted', max_length=20)),
                ('is_late', models.BooleanField(default=False)),
                ('first_submitted_at', models.DateTimeField()),
                ('last_submitted_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('teacher_feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='homework.assignmentrecipient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_submitted_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('answer_text', models.TextField(blank=True, default='')),
                ('answer_url', models.URLField(blank=True, default='', max_length=500)),
                ('submitted_at', models.DateTimeField()),
                ('is_late', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_homework_attempts', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='homework.assignmentsubmission')),
            ],
            options={
                'ordering': ('-revision', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['status', 'last_submitted_at'], name='hw_sub_status_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['submitted', 'reviewed'])), name='hw_submission_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('last_submitted_at__gte', models.F('first_submitted_at'))), name='hw_submission_valid_times'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('status', 'submitted')), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('status', 'reviewed')), _connector='OR'), name='hw_submission_review_state'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmissionattempt',
            index=models.Index(fields=['submission', 'submitted_at'], name='hw_attempt_sub_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmissionattempt',
            constraint=models.UniqueConstraint(fields=('submission', 'revision'), name='hw_unique_submission_revision'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmissionattempt',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='hw_attempt_positive_revision'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmissionattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('answer_text', ''), _negated=True), models.Q(('answer_url', ''), _negated=True), _connector='OR'), name='hw_attempt_has_content'),
        ),
    ]
