# Generated by Django 5.2.17 on 2026-09-28 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_groupmembership_group_students_and_more'),
        ('students', '0003_student_archived_at_student_status_before_archive'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_lessons', to='academics.group')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_lessons', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='academics.subject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('start_at', 'id'),
                'indexes': [models.Index(fields=['workspace', 'start_at'], name='lesson_ws_start_idx'), models.Index(fields=['workspace', 'status', 'start_at'], name='lesson_ws_status_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('student__isnull', False)), models.Q(('group__isnull', False), ('student__isnull', True)), _connector='OR'), name='lesson_exactly_one_target'), models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='lesson_valid_time_range')],
            },
        ),
    ]
