# Generated by Django 5.2.17 on 2026-09-29 11:17

import apps.lessons.db_expressions
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models

from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_groupmembership_group_students_and_more'),
        ('lessons', '0001_initial'),
        ('students', '0003_student_archived_at_student_status_before_archive'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['scheduled', 'completed'])), expressions=[(apps.lessons.db_expressions.TsTzRange('start_at', 'end_at', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('workspace', '=')], name='lesson_no_workspace_time_overlap'),
        ),
    ]
