# Generated by Django 5.2.17 on 2026-09-29 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_groupmembership_group_students_and_more'),
        ('lessons', '0003_lesson_cancellation_reason_lesson_cancelled_at_and_more'),
        ('students', '0003_student_archived_at_student_status_before_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attendance_initialized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LessonAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_attendances', to='academics.groupmembership')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='lessons.lesson')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_attendances', to='students.student')),
            ],
            options={
                'ordering': ('student__last_name', 'student__first_name', 'id'),
                'indexes': [models.Index(fields=['lesson', 'status'], name='attendance_lesson_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'student'), name='unique_lesson_attendance_student'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'present', 'absent', 'late', 'excused'])), name='lesson_attendance_valid_status'), models.CheckConstraint(condition=models.Q(models.Q(('recorded_at__isnull', True), ('recorded_by__isnull', True), ('status', 'pending')), models.Q(('status__in', ['present', 'absent', 'late', 'excused']), ('recorded_at__isnull', False), ('recorded_by__isnull', False)), _connector='OR'), name='attendance_recording_consistency')],
            },
        ),
    ]
